name: Main CI/CD
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  

env:
  CI: false
  env_main: ${{ secrets.ENV_MAIN }}

jobs:
  deploy:
    name: build && push image to Docker hub
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: import env file
        run: |
          touch ./.env && echo "$env_main" >> ./.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Hedera MUI Image
      - name: build && push kiichain-fe
        id: build-push-kiichain-fe
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha,scope=${{ github.ref_name }}-kiichain-fe
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-kiichain-fe
          file: Dockerfile
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: | 
            thespiritman/kiichain-frontend:${{ github.sha }}
            thespiritman/kiichain-frontend:main

      - name: Update Docker Image Tag
        uses: appleboy/ssh-action@v0.1.3
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export IMAGE_TAG=${{ github.sha }}
            cd /home/ubuntu/kiiChain-docker-projects/kiiChain-core && docker pull thespiritman/kiichain-frontend:$IMAGE_TAG && docker rm kiichain_fe -f && docker compose up kiichain_fe -d && docker image prune -f
          
                    